apiVersion: v2
name: server-app
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
- name: redis
  version: 18.11.0
  repository: https://charts.bitnami.com/bitnami
